Shell file errors more verbose

diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -1,5 +1,8 @@
 #!/bin/sh
-set -e
+err_report() {
+    echo "Clean.sh Failed"
+}
+trap 'err_report' ERR
 . ./config
 for PROJECT in $PROJECTS; do
   (cd $PROJECT && DESTDIR="$SYSROOT" make clean)
diff --git a/grub b/grub
--- a/grub
+++ b/grub
@@ -1,5 +1,8 @@
 #!/bin/sh
-set -e
+err_report() {
+    echo "Grub.sh Failed"
+}
+trap 'err_report' ERR
 . ./build
 export OUTISO="$(pwd)/$OSNAME.iso"
 (cd kernel && DESTDIR="$SYSROOT" make grub)
diff --git a/qemu b/qemu
--- a/qemu
+++ b/qemu
@@ -1,4 +1,7 @@
 #!/bin/sh
-set -e
+err_report() {
+    echo "Qemu.sh Failed"
+}
+trap 'err_report' ERR
 . ./build
 (cd kernel && DESTDIR="$SYSROOT" make run)
